### ISSUE TITLE
Set up Express route for authentication and authorization

### ISSUE THREAD

**Issue by Maryam-H-M** [gtaEPIC/COMP231-5-5W25#13]
User Story 2: A user can log in to the system and access his/her dashboard

**Comment by gtaEPIC** [comment]
Already added
Can be found [here](https://github.com/gtaEPIC/COMP231-5-5W25/blob/860844f2a4fd7b3882aaad767bc3f9526945e3c7/Backend/controllers/authController.js#L45)
