### ISSUE TITLE
Create MongoDB schema for storing customer ticket data

### ISSUE THREAD

**Issue by Maryam-H-M** [gtaEPIC/COMP231-5-5W25#24]
User Story 3: A customer can submit a ticket to the system

**Comment by gtaEPIC** [comment]
Already completed
Code can be found [here](https://github.com/gtaEPIC/COMP231-5-5W25/blob/860844f2a4fd7b3882aaad767bc3f9526945e3c7/Backend/models/ticket.js#L13)
