### ISSUE TITLE
Integrate React form with Express backend for ticket submission

### ISSUE THREAD

**Issue by Maryam-H-M** [gtaEPIC/COMP231-5-5W25#25]
User Story 3: A customer can submit a ticket to the system

**Comment by gtaEPIC** [comment]
Already completed
Handled per page:
[addTicket](https://github.com/gtaEPIC/COMP231-5-5W25/blob/main/Frontend/src/components/AddTicket.js)
[updateTicket](https://github.com/gtaEPIC/COMP231-5-5W25/blob/main/Frontend/src/components/UpdateTicket.js)
[deleteTicket](https://github.com/gtaEPIC/COMP231-5-5W25/blob/main/Frontend/src/components/DeleteTicket.js)
