### ISSUE TITLE
Validate and sanitize user inputs in the ticket submission form

### ISSUE THREAD

**Issue by Maryam-H-M** [gtaEPIC/COMP231-5-5W25#27]
User Story 3: A customer can submit a ticket to the system

**Comment by gtaEPIC** [comment]
Completed already
Code can be found [here](https://github.com/gtaEPIC/COMP231-5-5W25/blob/860844f2a4fd7b3882aaad767bc3f9526945e3c7/Frontend/src/components/AddTicket.js#L19)
