### ISSUE TITLE
Set up Express routes to fetch customer’s submitted tickets from MongoDB

### ISSUE THREAD

**Issue by Maryam-H-M** [gtaEPIC/COMP231-5-5W25#29]
User Story 4: A customer can access their submitted tickets

**Comment by gtaEPIC** [comment]
Already completed
[All tickets page](https://github.com/gtaEPIC/COMP231-5-5W25/blob/main/Frontend/src/components/Tickets.js)
[User dashboard](https://github.com/gtaEPIC/COMP231-5-5W25/blob/860844f2a4fd7b3882aaad767bc3f9526945e3c7/Frontend/src/components/Main.js#L15-L30)
