### ISSUE TITLE
Set up Express route to fetch authorization data and ticket details from MongoDB

### ISSUE THREAD

**Issue by Maryam-H-M** [gtaEPIC/COMP231-5-5W25#32]
User Stories 5-7-11: A user can access the details and audit trail of a ticket they are authorized to view

**Comment by gtaEPIC** [comment]
Already completed
[Authorization](https://github.com/gtaEPIC/COMP231-5-5W25/blob/main/Backend/controllers/authController.js)
[Ticket Handler](https://github.com/gtaEPIC/COMP231-5-5W25/blob/860844f2a4fd7b3882aaad767bc3f9526945e3c7/Backend/controllers/ticketController.js#L6-L47)
